global using Core.CQRS;
global using Carter;
global using MediatR;
global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using System.Text.Json;
global using DeviceManagement.API.Extensions;
global using MongoDB.Driver;
global using MongoDB.Bson;
